// @ts-check
"use strict";
/* ============================================================================
   glossary-world.js — the glossary as a place, not a page.

   Two bodies of words stand on one circuit, and the slime walks it:

   THE WHOLE OF IT IS UNDERGROUND. One cave, in two halves:

     GLOSSARY      the author's own coinages, on posts in a living cavern. Vines
                   hang from the roof, moss banks the plinths, and light falls
                   in shafts through cracks overhead.
     ANTIGLOSSARY  the penumbra. Notes an AI wrote about what the corpus does
                   NOT say. Past the inner threshold the light goes out, the
                   roof drops to stalactites, and these hang in the middle
                   distance, behind the walking plane and out of reach.

   The way in is at the seam, where a shaft of daylight comes down from the
   Glossary house on the road above. Nothing grows and nothing is built in
   here: no trees, no houses, only rock, water and what took hold in the dark.

   THE ORDER IS THE ARGUMENT. The circuit runs from the words the field already
   uses to the ones that exist nowhere but here: borrowed, then extended, then
   coined, then invented by a machine, then round to ordinary language again.
   The ground keeps score. It is smooth where the vocabulary is shared and
   breaks up as the coinages get stranger, so the walking is hardest where the
   words are newest. glossary-data.js carries the rank that drives both.

   The words themselves come from glossary-data.js, generated by
   brand/backstage/build-glossary-data.py out of the lexicon and the Zotero
   collection. The same script writes the plain-text lists further down the
   page, so the crawl and the lists can never disagree; the lists are also the
   whole content without a canvas, a pointer, or a single frame of animation.

   The creature is slime-2d.js, the site's slime as a body with a skin: its
   underside takes the shape of the ground it is lying on, so the walk over the
   plinths and down into the fissure is the point of using it here.

   The circuit, the camera, the walk, the water and the keys are engine-side.js
   (MH_SIDE), shared with any other sidescrolling world. This file is only what
   makes this one the glossary: the shape of the cave, its two palettes, what
   grows in it, the boards and their words, and the card under the strip.
   ========================================================================== */
(function () {
  const DATA = window.MH_GLOSSARY, S2 = window.MH_SLIME2D, SIDE = window.MH_SIDE;
  const cv = /** @type {HTMLCanvasElement|null} */ (document.getElementById("crawl"));
  const card = document.getElementById("entry");
  const bar = document.getElementById("trail");
  if (!DATA || !S2 || !SIDE || !cv || !card) return;        // the lists still read fine

  const reduce = !!(window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches);
  const g = /** @type {CanvasRenderingContext2D} */ (cv.getContext("2d"));
  const FONT = '600 11px Tahoma, Arial, sans-serif';
  const LINE = 14, PAD = 8;                      // line height, and the air above and below it
  const SIGN_FONT = '700 15px Tahoma, Arial, sans-serif';

  const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
  // How far back the antiglossary hangs. Parallax about the centre of the view,
  // so a background sign is in front of the slime exactly when it shares its
  // world x, and everything else about it moves at BACK of the rate.
  const BACK = 0.55, BACK_SCALE = 0.8;
  const T = (key, en) => (window.MH_I18N ? window.MH_I18N.t(key, en) : en);
  /** French is a full translation here, definitions and all, so the page asks
   *  outright rather than going through the dictionary for every gloss. */
  const french = () => !!(window.MH_I18N && window.MH_I18N.lang === "fr");
  const say = (e, field) => (french() && e[field + "Fr"] ? e[field + "Fr"] : e[field]);
  /** What goes on the board. In French the terms are French too, where a French
   *  coinage exists for them; the English is kept beside it in the card. */
  const label = (m) => say(m.e, "term");

  /* ── the circuit ───────────────────────────────────────────────────────
     It closes: walk far enough in either direction and the most invented word
     hands back to the most ordinary one. Every position is modulo worldW, and
     every distance is the shorter way round. */
  const LEAD = 260, STEP = 178, GAP = 440, RETURN = 820;
  const NG = DATA.glossary.length, NP = DATA.antiglossary.length;
  const marks = [];
  DATA.glossary.forEach((e, i) => marks.push(
    { x: LEAD + i * STEP, side: "glossary", i: i, e: e, title: e.term, row: i % 3 }));
  const lastG = LEAD + Math.max(0, NG - 1) * STEP;
  const firstPen = LEAD + NG * STEP + GAP;
  const gateX = LEAD + NG * STEP + GAP / 2;
  // Two rows, not three: set back and scaled down, they crowd each other in the
  // middle distance faster than the foreground does.
  DATA.antiglossary.forEach((e, i) => marks.push(
    { x: firstPen + i * STEP, side: "penumbra", i: i, e: e, title: e.term, row: i % 2 }));
  const lastPen = firstPen + Math.max(0, NP - 1) * STEP;
  const worldW = lastPen + RETURN;               // the climb back out to the start
  const TAU = Math.PI * 2;
  // The inner threshold, where the living half gives way to the dark one. The
  // roof drops over MOUTH pixels, the floor steps under it, and the light goes
  // with it. ENTRY is the way in from the road above, at the seam.
  const MOUTH = 300, entryX = gateX, exitX = lastPen + 210;
  const ROOF_LIT = 18, ROOF_DARK = 40, ENTRY_W = 260;

  const wrap = (x) => ((x % worldW) + worldW) % worldW;
  // A spacing that divides the circuit exactly, so growth repeats once around it
  // and nothing jumps at the seam.
  const every = (aim) => worldW / Math.max(1, Math.round(worldW / aim));
  /** The shorter way round, in (-worldW/2, worldW/2]. */
  function rd(d) {
    d = ((d % worldW) + worldW) % worldW;
    return d > worldW / 2 ? d - worldW : d;
  }
  const lerp = (a, b, t) => a + (b - a) * t;
  const smooth = (t) => { t = clamp(t, 0, 1); return t * t * (3 - 2 * t); };

  /* How new the words are here: 0 where the field already talks this way, 1
     where nothing outside this corpus does. It drives the order of the walk,
     the roughness of the ground, and nothing else. Continuous round the loop,
     including across the seam, or the ground would have a cliff in it. */
  const ranks = DATA.glossary.map((e) => (e.rank == null ? 0.6 : e.rank));
  function rough(x) {
    if (!NG) return 0;
    if (x < LEAD) return ranks[0] * (x / LEAD);               // easing in from the seam
    if (x <= lastG) {
      const f = (x - LEAD) / STEP, i = Math.min(NG - 1, Math.floor(f));
      return lerp(ranks[i], ranks[Math.min(NG - 1, i + 1)], f - i);
    }
    if (x < firstPen) return lerp(ranks[NG - 1], 1, (x - lastG) / (firstPen - lastG));
    if (x < exitX) return 1;                                  // the cave: all invention
    return 1 - (x - exitX) / (worldW - exitX);                // and the climb back out
  }

  /** How far into the DARK half x is: 0 in the living cavern, 1 deep in the
   *  penumbra. One number drives the roof's height, the palette and the light. */
  function caveT(x) {
    const a = smooth(rd(x - entryX) / MOUTH + 0.5);
    const b = 1 - smooth(rd(x - exitX) / MOUTH + 0.5);
    return clamp(Math.min(a, b), 0, 1);
  }
  const darkAt = caveT;

  /** How close x is to the way in: 1 at the seam, 0 a screen away. The roof
   *  opens there, and the daylight that falls through is the only daylight. */
  function entryT(x) {
    const d = Math.abs(rd(x - 0));
    return d > ENTRY_W ? 0 : smooth(1 - d / ENTRY_W);
  }

  /** The underside of the rock overhead. There is always rock overhead, except
   *  directly under the way in, where it opens to the sky. */
  function roofAt(x) {
    const th = TAU * wrap(x) / worldW;
    const lift = lerp(ROOF_LIT, ROOF_DARK, caveT(x));
    const bumps = 7 * Math.sin(th * 137 + 1.1) + 4 * Math.sin(th * 263 + 0.4);
    return lift + bumps - entryT(x) * (lift + bumps + 80);
  }

  // Which markers can affect the ground at x, without walking the whole line
  // sixty times a second.
  const BUCKET = 128, bucketed = new Map();
  marks.forEach((m) => {
    if (m.side !== "glossary") return;                        // the penumbra stands on nothing
    for (let b = Math.floor((m.x - 90) / BUCKET); b <= Math.floor((m.x + 90) / BUCKET); b++) {
      const k = ((b % Math.ceil(worldW / BUCKET)) + Math.ceil(worldW / BUCKET)) % Math.ceil(worldW / BUCKET);
      if (!bucketed.has(k)) bucketed.set(k, []);
      bucketed.get(k).push(m);
    }
  });
  const BUCKETS = Math.ceil(worldW / BUCKET);

  /* ── the ground ────────────────────────────────────────────────────── */

  /** Where a marker lands on screen. `cam` is the world point at the CENTRE of
   *  the view, so the foreground walks with the camera and the penumbra, moving
   *  at BACK of that rate, is in front of the slime exactly when it shares its
   *  world x. */
  function screenX(m) {
    const d = rd(m.x - S.cam);
    return S.W / 2 + (m.side === "penumbra" ? d * BACK : d);
  }

  function ground(x) {
    x = wrap(x);
    // Whole-number harmonics of the circuit, so the ground meets itself at the
    // seam with no step in it.
    const th = TAU * x / worldW;
    let y = S.base
      - 5.0 * Math.sin(th * 7)
      - 2.6 * Math.sin(th * 17 + 1.7)
      - 1.3 * Math.sin(th * 41 + 3.1);
    const r = rough(x);                                      // rockier among the coinages
    if (r > 0.001) y -= r * (4.2 * Math.sin(th * 97 + 0.3)
      + 2.6 * Math.sin(th * 173 + 2.2) + 1.5 * Math.sin(th * 331 + 5.1));
    y += 16 * caveT(x);                                      // the dark half lies lower
    const din = rd(x - entryX), dout = rd(x - exitX);        // a step down in, a step up out
    y += 26 * Math.exp(-(din * din) / (2 * 70 * 70));
    y += 20 * Math.exp(-(dout * dout) / (2 * 70 * 70));
    y -= 22 * entryT(x);                                     // the floor rises to the way in
    const near = bucketed.get(((Math.floor(x / BUCKET) % BUCKETS) + BUCKETS) % BUCKETS);
    if (near) for (let i = 0; i < near.length; i++) {         // a plinth under every word
      const u = rd(x - near[i].x);
      y -= 7 * Math.exp(-(u * u) / (2 * 34 * 34));
    }
    return y;
  }

  /* ── two palettes, crossfaded as you cross ─────────────────────────── */
  // The living half: a cavern with things growing in it, lit through cracks.
  const DAY = { skyTop: "#3d6049", skyBot: "#25382c", hill: "#47513f", hill2: "#363f31",
    rock: "#5b5343", rockLo: "#3f3a2e", ink: "#0c120c", inkA: 0.85, post: "#8b8172",
    plaque: "#f6f4ee", plaqueLit: "#c3f0ff", text: "#1a1a1a", dust: "#cfeeb6", dustA: 0.5 };
  // The dark half is gloomthmaxx: theme-technoscure.js's own colours, fonts and
  // sign format, so the cave belongs to the same world as the site after dark.
  const GOLD = "#caa24a", TEAL = "#3a8a82", IRON = "#14160f", BONE = "#cdbf9a";
  const CAVE_FONT = '700 11px "Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif';
  const CAVE_SIGN_FONT = '700 15px "Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif';
  const PEN = { skyTop: "#070b08", skyBot: "#12160f", hill: "#14160f", hill2: "#0d0f0a",
    rock: "#23261c", rockLo: IRON, ink: BONE, inkA: 0.5, post: TEAL,
    plaque: "#11180f", plaqueLit: "#1d2a1c", text: GOLD, dust: TEAL, dustA: 0.5 };

  /** theme-technoscure.js's glow, to the letter: a bloom that reduced motion turns off. */
  function glow(x, y, r, col, blur) {
    g.save();
    if (!reduce) { g.shadowColor = col; g.shadowBlur = blur; }
    g.fillStyle = col; g.beginPath(); g.arc(x, y, r, 0, TAU); g.fill();
    g.restore();
  }

  const mix = SIDE.mix, rgba = SIDE.rgba;

  /** How far into the penumbra the VIEW is: 0 daylight, 1 dark. */
  function dusk() { return darkAt(S.cam); }
  function pal() {
    const t = dusk(), P = {};
    ["skyTop", "skyBot", "hill", "hill2", "rock", "rockLo", "post", "plaque", "plaqueLit", "text"]
      .forEach((k) => { P[k] = mix(DAY[k], PEN[k], t); });
    P.ink = mix(DAY.ink, PEN.ink, t);
    P.inkA = DAY.inkA + (PEN.inkA - DAY.inkA) * t;
    P.stroke = rgba(t < 0.5 ? DAY.ink : PEN.ink, P.inkA);
    P.dust = t < 0.5 ? rgba(DAY.dust, DAY.dustA * (1 - t)) : rgba(PEN.dust, PEN.dustA * t);
    P.t = t;
    return P;
  }

  /* ── labels, wrapped once and remembered ───────────────────────────── */
  function lines(m) {
    if (m.lines) return m.lines;
    const back = m.side === "penumbra";
    const wide = back ? 176 : 150, cap = back ? 2 : 3;
    g.font = back ? CAVE_FONT : FONT;
    const words = String(label(m)).split(/\s+/), out = [];
    let line = "", cut = false;
    for (let i = 0; i < words.length; i++) {
      const next = line ? line + " " + words[i] : words[i];
      if (g.measureText(next).width > wide && line) { out.push(line); line = words[i]; }
      else line = next;
      if (out.length === cap) { cut = i < words.length - 1; break; }
    }
    if (out.length < cap && line) out.push(line);
    if (cut) {                                               // a long note keeps its full title in the card
      let last = out[cap - 1];
      while (g.measureText(last + "…").width > wide && last.length > 4) last = last.slice(0, -1);
      out[cap - 1] = last.replace(/[ ,;:]$/, "") + "…";
    }
    m.lines = out;
    m.w = Math.max.apply(null, out.map((l) => g.measureText(l).width)) + 20;
    m.h = out.length * LINE + PAD * 2;
    return out;
  }

  /* ── what grows in here ────────────────────────────────────────────────
     A cave has no trees and no buildings in it. The living half has vines off
     the roof, moss banked against the plinths and light coming down through
     cracks; the dark half has stalactites and nothing alive. Everything is
     drawn from the world's own coordinates, so it holds still as the slime
     passes and repeats exactly once around the circuit.                      */

  /** A vine off the roof. Long ones reach the floor and root there. */
  function vine(x, t, P, dark) {
    const w = wrap(x);                                       // its place on the circuit
    const from = roofAt(x), lit = 1 - dark;
    if (lit < 0.05 || from < -40) return;
    const span = 34 + ((Math.abs(Math.sin(w * 0.037)) * 78) | 0);
    const to = Math.min(from + span, ground(x) - 2);
    const sway = reduce ? 0 : Math.sin(t * 0.7 + w * 0.03) * 4;
    const sx = S.W / 2 + rd(x - S.cam);
    g.save(); g.globalAlpha = lit;
    g.strokeStyle = "#4f7d4a"; g.lineWidth = 2.2; g.lineCap = "round";
    g.beginPath(); g.moveTo(sx, from);
    g.bezierCurveTo(sx + sway, from + (to - from) * 0.4, sx - sway, from + (to - from) * 0.76, sx + sway * 0.4, to);
    g.stroke();
    const n = Math.max(2, Math.round((to - from) / 26));
    for (let i = 1; i <= n; i++) {
      const u = i / (n + 1), y = from + (to - from) * u, side = i % 2 ? 1 : -1;
      g.fillStyle = "#7fb46a";
      g.beginPath(); g.ellipse(sx + side * 4 + sway * u, y, 5, 2.5, side * -0.5, 0, TAU); g.fill();
      g.strokeStyle = P.stroke; g.lineWidth = 0.9; g.stroke();
      g.strokeStyle = "#4f7d4a"; g.lineWidth = 2.2;
    }
    g.restore();
  }

  /** A pool of light lying ON the floor: out along the ground, back along a
   *  lens above it. A flat ellipse floats wherever the floor is not flat. */
  function lightPool(x, r, rise, fill) {
    const N = 20;
    g.beginPath();
    for (let i = 0; i <= N; i++) {
      const u = -1 + (2 * i) / N, wx = x + u * r;
      const sx = S.W / 2 + rd(wx - S.cam);
      i ? g.lineTo(sx, ground(wx) + 1.5) : g.moveTo(sx, ground(wx) + 1.5);
    }
    for (let i = N; i >= 0; i--) {
      const u = -1 + (2 * i) / N, wx = x + u * r;
      g.lineTo(S.W / 2 + rd(wx - S.cam), ground(wx) - Math.cos(u * Math.PI / 2) * rise);
    }
    g.closePath(); g.fillStyle = fill; g.fill();
  }

  /** Daylight down a crack, and the patch of floor it finds. */
  function crack(x, t, P, dark) {
    const lit = 1 - dark;
    if (lit < 0.06) return;
    const sx = S.W / 2 + rd(x - S.cam), top = roofAt(x), floor = ground(x);
    if (top > floor - 20) return;
    const grad = g.createLinearGradient(0, top, 0, floor);
    grad.addColorStop(0, "rgba(207,238,182," + (0.30 * lit).toFixed(3) + ")");
    grad.addColorStop(1, "rgba(207,238,182,0)");
    g.fillStyle = grad;
    g.beginPath();
    g.moveTo(sx - 8, top); g.lineTo(sx + 8, top);
    g.lineTo(sx + 26, floor); g.lineTo(sx - 26, floor); g.closePath(); g.fill();
    lightPool(x, 26, 4.5, "rgba(207,238,182," + (0.18 * lit).toFixed(3) + ")");
  }

  /** Moss banked against a plinth. Its underside IS the floor: the shape goes
   *  out along a jagged crown and comes back along the ground it sits on, so it
   *  can never float over a curve the way a straight closing edge did. */
  function mossOn(x, P, dark) {
    const lit = 1 - dark;
    if (lit < 0.08) return;
    if (S.poolAt(x)) return;                                 // a plinth under the water grows no moss
    const r = 23, N = 16;
    g.save(); g.globalAlpha = lit;
    g.beginPath();
    for (let i = 0; i <= N; i++) {
      const u = -1 + (2 * i) / N, wx = x + u * r;
      const bristle = 1 + 0.42 * Math.sin(i * 2.7 + wrap(x) * 0.05);
      const h = Math.max(0, Math.cos(u * Math.PI / 2) * 9 * bristle);
      const sx = S.W / 2 + rd(wx - S.cam);
      i ? g.lineTo(sx, ground(wx) - h) : g.moveTo(sx, ground(wx) - h);
    }
    for (let i = N; i >= 0; i--) {                           // home along the floor
      const u = -1 + (2 * i) / N, wx = x + u * r;
      g.lineTo(S.W / 2 + rd(wx - S.cam), ground(wx) + 1.5);
    }
    g.closePath();
    const gy = ground(x);
    const grad = g.createLinearGradient(0, gy - 11, 0, gy + 2);
    grad.addColorStop(0, "#5d9152"); grad.addColorStop(1, "#3c6438");
    g.fillStyle = grad; g.fill();
    g.strokeStyle = P.stroke; g.lineWidth = 1.4; g.lineJoin = "round"; g.stroke();
    g.restore();
  }

  /** The way in: a shaft of real daylight, and the steps under it. */
  function wayIn(P) {
    const t0 = entryT(S.cam + 0);
    if (Math.abs(rd(0 - S.cam)) > S.W) return;
    const sx = S.W / 2 + rd(0 - S.cam), floor = ground(0);
    const grad = g.createLinearGradient(0, -20, 0, floor);
    grad.addColorStop(0, "rgba(232,246,224,0.62)"); grad.addColorStop(1, "rgba(232,246,224,0)");
    g.fillStyle = grad;
    g.beginPath();
    g.moveTo(sx - 42, -20); g.lineTo(sx + 42, -20);
    g.lineTo(sx + 64, floor); g.lineTo(sx - 64, floor); g.closePath(); g.fill();
    lightPool(0, 58, 8, "rgba(232,246,224,0.26)");           // the patch of floor it finds
    return t0;
  }

  /** technoscure's lighting: the world sinks to black except where the slime is,
   *  which carries its own light. Multiply, so the dark takes the colour with it. */
  function gloom(P, mx, my) {
    if (P.t < 0.02) return;
    g.save();
    g.globalAlpha = P.t; g.globalCompositeOperation = "multiply";
    const lamp = g.createRadialGradient(mx, my, 8, mx, my, Math.max(S.W, S.H) * 0.95);
    lamp.addColorStop(0, "#ffffff"); lamp.addColorStop(0.18, "#dbe3d6");
    lamp.addColorStop(0.46, "#9aa498"); lamp.addColorStop(1, "#4a564e");   // never quite pitch: the ruins have to read
    g.fillStyle = lamp; g.fillRect(0, 0, S.W, S.H);
    g.restore();
  }

  /** and the heavy vignette that closes around the edges after dark. */
  function vignette(P) {
    if (P.t < 0.02) return;
    const v = g.createRadialGradient(S.W / 2, S.H / 2, Math.min(S.W, S.H) * 0.3, S.W / 2, S.H / 2, Math.max(S.W, S.H) * 0.8);
    v.addColorStop(0, "rgba(3,5,4,0)"); v.addColorStop(1, "rgba(3,5,4," + (0.62 * P.t).toFixed(3) + ")");
    g.fillStyle = v; g.fillRect(0, 0, S.W, S.H);
  }

  /* ── standing water: the engine's pools, in this cave's colours ──── */
  /* The iso lakes' photo of real water (water.webp) shows through where the
     water is deep: faint under the surface, clearer toward the bottom, and
     darkened in the dark half. Only here; nothing else in the cave is a photo. */
  const photo = { img: null, ready: false, pat: null };
  if (typeof Image !== "undefined") {
    photo.img = new Image();
    photo.img.onload = () => { photo.ready = true; };
    photo.img.src = ((window.MH_SITE && window.MH_SITE.base) || "") + "water.webp";
  }
  function underWater(g, q, x0, x1, top, bot) {
    if (!photo.ready || bot - top < 14) return;              // a shallow puddle stays drawn
    if (!photo.pat) photo.pat = g.createPattern(photo.img, "repeat");
    const k = 0.9;                                            // the photo at about its own size, so it keeps its grain
    if (photo.pat.setTransform) photo.pat.setTransform(new DOMMatrix([k, 0, 0, k, x0, top]));
    g.fillStyle = photo.pat; g.fillRect(x0, top, x1 - x0, bot - top);
    const dark = caveT(S.cam) >= 0.5;
    const fade = g.createLinearGradient(0, top, 0, bot);      // deep is where it shows
    fade.addColorStop(0, dark ? "rgba(6,16,14,0.9)" : "rgba(120,220,200,0.85)");
    fade.addColorStop(Math.min(0.6, 14 / (bot - top) + 0.2), dark ? "rgba(6,16,14,0.55)" : "rgba(120,220,200,0.35)");
    fade.addColorStop(1, dark ? "rgba(6,16,14,0.45)" : "rgba(16,60,56,0.15)");
    g.fillStyle = fade; g.fillRect(x0, top, x1 - x0, bot - top);
  }
  function drawWater(P) {
    S.drawWater((q, top, bot) => {
      const grad = g.createLinearGradient(0, top, 0, bot);
      if (caveT(S.cam) < 0.5) { grad.addColorStop(0, "rgba(120,220,200,0.44)"); grad.addColorStop(1, "rgba(16,60,56,0.72)"); }
      else { grad.addColorStop(0, "rgba(58,138,130,0.40)"); grad.addColorStop(1, "rgba(6,16,14,0.82)"); }
      return grad;
    }, (q) => (caveT(S.cam) < 0.5 ? "rgba(205,250,240,0.8)" : "rgba(160,220,210,0.5)"), underWater);
  }

  /* ── the engine: circuit, camera, body, water, and the keys ───────── */
  let active = null;
  /* On a phone the card covers the slime, and the slime is the reader's
     cursor: walking past the words must not bury it. There a word's card
     shows only when the reader taps that word (or asks for it by address or
     from the word list), once the slime has reached it, and it goes when the
     slime walks on or the reader taps anywhere else. */
  const tapOnly = window.matchMedia ? window.matchMedia("(max-width: 620px), (pointer: coarse) and (max-height: 620px)") : null;
  let pinned = null, reached = false;                        // the word tapped, and whether the slime has got there
  const S = SIDE.create(cv, {
    worldW,
    ground: (x) => ground(x),
    // One water table for the whole cave (see engine-side.js). The dark half
    // lies lower, so the line chosen here decides how much of it is flooded.
    water: { flood: 0.15, max: 16 },
    // The floor line sits higher than the engine's default, so the card under
    // the strip reads clear below the slime rather than beside it.
    fit: { baseFrac: 0.36, baseMin: 128 },
    draw: () => draw(),
    onStep: () => {
      read();
      if (bar) bar.querySelector(".dot").style.left = (S.me.x / worldW * 100) + "%";
    },
    onSize: () => {
      const barEl = document.getElementById("mh-menubar");   // it can wrap to two rows
      document.documentElement.style.setProperty("--mh-bar", (barEl ? barEl.offsetHeight : 46) + "px");
      marks.forEach((m) => { m.lines = null; });
      if (bar) {
        // The light changes over the mouths, not at a line, so the bar does too.
        const pc = (x) => (wrap(x) / worldW * 100).toFixed(2) + "%";
        const DAYC = "#bcdcc7", DARKC = "#242a20";
        bar.style.background = "linear-gradient(90deg,"
          + DAYC + " 0%," + DAYC + " " + pc(entryX - MOUTH / 2) + ","
          + DARKC + " " + pc(entryX + MOUTH / 2) + "," + DARKC + " " + pc(exitX - MOUTH / 2) + ","
          + DAYC + " " + pc(exitX + MOUTH / 2) + "," + DAYC + " 100%)";
        bar.hidden = false;
      }
    },
    // Home and PageUp to the first word, End to the strangest, PageDown into the dark.
    keys: { Home: () => S.go(LEAD), PageUp: () => S.go(LEAD), End: () => S.go(lastG), PageDown: () => S.go(gateX + 150) },
  });
  S.me.x = S.cam = wrap(LEAD - 170);


  function roundRect(x, y, w, h, r) {
    g.beginPath();
    g.moveTo(x + r, y);
    g.arcTo(x + w, y, x + w, y + h, r); g.arcTo(x + w, y + h, x, y + h, r);
    g.arcTo(x, y + h, x, y, r); g.arcTo(x, y, x + w, y, r);
    g.closePath();
  }

  /* ── drawing ───────────────────────────────────────────────────────── */
  function ridge(P, depth, fill, amp, lift) {
    const y0 = S.base - 58 - amp - (lift || 0), span = worldW * depth;
    g.beginPath(); g.moveTo(0, S.H);
    for (let sx = 0; sx <= S.W; sx += 6) {
      const th = TAU * (S.cam * depth + sx - S.W / 2) / span;    // one whole number of waves
      g.lineTo(sx, y0 + amp * (Math.sin(th * 7) + 0.5 * Math.sin(th * 17 + 1.2)));
    }
    g.lineTo(S.W, S.H); g.closePath(); g.fillStyle = fill; g.fill();
  }

  /** The band of air the antiglossary hangs in, above both ridges. */
  function backBand() {
    const bottom = S.base - 96, top = ROOF_DARK + 36;          // clear of the rock and its teeth
    return { bottom: bottom, gap: clamp(bottom - top - 40, 34, 130) };
  }

  /** What a hung board dangles from: a tentacle out of the rock, thick where it
   *  leaves the ceiling and tapering to the grip. Same construction as the
   *  shoggoths' limbs in ecology.js, round-capped segments under an ink pass,
   *  drawn at full scale AFTER the rock so nothing covers it. */
  function tentacle(sx, y0, y1, t) {
    const len = y1 - y0;
    if (len < 4) return;
    const M = 5, curl = reduce ? 0 : Math.sin(t * 0.9 + sx * 0.03) * 0.42;
    const px = [sx], py = [y0];
    for (let i = 1; i <= M; i++) {
      const u = i / M;
      px.push(sx + Math.sin(u * 2.1) * curl * 13);
      py.push(y0 + len * u);
    }
    g.lineCap = "round"; g.lineJoin = "round";
    for (let pass = 0; pass < 2; pass++) {
      g.strokeStyle = pass ? "#46525a" : "rgba(8,12,10,0.9)";
      for (let i = 0; i < M; i++) {
        g.lineWidth = (4.4 * (1 - i / M) + 1.1) + (pass ? 0 : 2);
        g.beginPath(); g.moveTo(px[i], py[i]); g.lineTo(px[i + 1], py[i + 1]); g.stroke();
      }
    }
    g.strokeStyle = "rgba(150,190,200,0.34)"; g.lineWidth = 1;    // the wet sheen down one side
    g.beginPath();
    for (let i = 0; i <= M; i++) {
      const w = 4.4 * (1 - i / M) + 1.1;
      i ? g.lineTo(px[i] - w * 0.4, py[i]) : g.moveTo(px[i] - w * 0.4, py[i]);
    }
    g.stroke();
    for (let i = 1; i < M; i++) {                                 // a few suckers
      const w = 4.4 * (1 - i / M) + 1.1;
      g.fillStyle = "rgba(20,28,26,0.55)";
      g.beginPath(); g.arc(px[i] + w * 0.35, py[i], Math.max(0.8, w * 0.32), 0, TAU); g.fill();
    }
  }

  function marker(m, P, pass) {
    const back = m.side === "penumbra";
    const sx = screenX(m), ls = lines(m), lit = m === active;
    let gy, post, top;
    if (back) {
      const b = backBand();
      gy = b.bottom - m.row * b.gap;                        // nothing holds it up
      post = 0;
      top = Math.max(4, gy - m.h);
    } else {
      gy = ground(m.x);
      post = 44 + m.row * 24;
      top = gy - post - m.h;
    }
    g.save();
    if (back) {                                            // set back: smaller, hazier
      g.translate(sx, gy); g.scale(BACK_SCALE, BACK_SCALE); g.translate(-sx, -gy);
      g.globalAlpha = 0.86;
    }
    if (!back) {
      g.strokeStyle = P.stroke; g.lineWidth = 4.5; g.lineCap = "round";
      g.beginPath(); g.moveTo(sx, gy - 2); g.lineTo(sx, gy - post + 2); g.stroke();
      g.strokeStyle = P.post; g.lineWidth = 2.4;
      g.beginPath(); g.moveTo(sx, gy - 3); g.lineTo(sx, gy - post + 3); g.stroke();
    }
    // A board in the dark is theme-technoscure.js's signpost: near-black fill,
    // a teal rule round it, gold letters in the gloom serif, and a bead of light
    // where it hangs. In daylight it is the site's parchment plaque.
    if (lit && !back) { g.save(); g.shadowColor = P.plaqueLit; g.shadowBlur = 16; }
    roundRect(sx - m.w / 2, top, m.w, m.h, back ? 4 : 7);
    g.fillStyle = lit && !back ? P.plaqueLit : P.plaque; g.fill();
    if (lit && !back) g.restore();
    if (back) {
      g.strokeStyle = TEAL; g.lineWidth = lit ? 2.4 : 1.6; g.stroke();
      g.font = CAVE_FONT; g.fillStyle = lit ? "#e8d9a6" : GOLD;
    } else {
      g.strokeStyle = P.stroke; g.lineWidth = lit ? 2.2 : 1.4; g.stroke();
      g.font = FONT; g.fillStyle = "#1a1a1a";
    }
    g.textAlign = "center"; g.textBaseline = "middle";
    for (let i = 0; i < ls.length; i++) g.fillText(ls[i], sx, top + PAD + LINE * i + LINE / 2);
    if (back) glow(sx, top + 2, lit ? 2.6 : 1.7, lit ? GOLD : TEAL, lit ? 12 : 7);
    if (m.read && !lit) {                                    // a bead for every word already read
      g.fillStyle = back ? TEAL : "#4FA373";
      if (back) { g.beginPath(); g.arc(sx + m.w / 2 - 7, top + m.h - 6, 2.2, 0, TAU); g.fill(); }
      else { g.beginPath(); g.arc(sx, gy - 3, 2.6, 0, TAU); g.fill(); }
    }
    g.restore();
  }

  /** A standing sign that announces a half of the cave, and says in a line what
   *  that half is. Two boards on one pair of posts, in the same format as the
   *  word boards around it: parchment in the living half, and in the dark
   *  technoscure's own, near-black behind a teal rule with gold serif letters. */
  function sign(x, label, P, pen, note) {
    const sx = S.W / 2 + rd(x - S.cam), gy = ground(x);
    g.font = pen ? CAVE_SIGN_FONT : SIGN_FONT;
    let lines2 = [];
    if (note) {                                              // wrap the explanation
      g.font = pen ? CAVE_FONT : FONT;
      const words = String(note).split(/\s+/);
      let line = "";
      for (let i = 0; i < words.length; i++) {
        const next = line ? line + " " + words[i] : words[i];
        if (g.measureText(next).width > 150 && line) { lines2.push(line); line = words[i]; }
        else line = next;
      }
      if (line) lines2.push(line);
      g.font = pen ? CAVE_SIGN_FONT : SIGN_FONT;
    }
    const noteH = lines2.length ? lines2.length * LINE + PAD * 2 + 6 : 0;
    const noteW = lines2.length                                // exactly a word board's width
      ? Math.max.apply(null, lines2.map((l) => { g.font = pen ? CAVE_FONT : FONT; return g.measureText(l).width; })) + 20
      : 0;
    g.font = pen ? CAVE_SIGN_FONT : SIGN_FONT;
    const w = g.measureText(label).width + 30;
    const h = 30, top = gy - 96 - noteH;
    g.strokeStyle = pen ? "#1a140c" : P.stroke; g.lineWidth = 5; g.lineCap = "round";
    g.beginPath(); g.moveTo(sx - w / 4, gy); g.lineTo(sx - w / 4, top + h);
    g.moveTo(sx + w / 4, gy); g.lineTo(sx + w / 4, top + h); g.stroke();
    roundRect(sx - w / 2, top, w, h, pen ? 4 : 9);
    g.fillStyle = pen ? "#11180f" : "#f6f4ee"; g.fill();
    g.strokeStyle = pen ? TEAL : P.stroke; g.lineWidth = 2; g.stroke();
    g.fillStyle = pen ? GOLD : "#1a1a1a";
    g.textAlign = "center"; g.textBaseline = "middle";
    g.fillText(label, sx, top + h / 2 + 1);
    if (pen) glow(sx, top - 4, 2.6, GOLD, 10);
    if (!lines2.length) return;
    // The explanation is a glossary entry, in the format every word here uses:
    // the same width rule, the same radius, the same rule weight, the same type.
    const ny = top + h + 8;
    roundRect(sx - noteW / 2, ny, noteW, noteH - 6, pen ? 4 : 7);
    g.fillStyle = pen ? P.plaque : P.plaque; g.fill();
    g.strokeStyle = pen ? TEAL : P.stroke; g.lineWidth = 1.4; g.stroke();
    g.font = pen ? CAVE_FONT : FONT;
    g.fillStyle = pen ? GOLD : "#1a1a1a";
    for (let i = 0; i < lines2.length; i++) {
      g.fillText(lines2[i], sx, ny + PAD + LINE * i + LINE / 2);
    }
  }

  /** The rock overhead. Its teeth are vertices of the same outline, so there is
   *  one silhouette and one stroke: a stalactite is the ceiling coming to a
   *  point, not a triangle laid under it. */
  /** The ceiling's underside in screen space, teeth included. Used to draw the
   *  rock, and to clip whatever must appear to come out of it. */
  function roofOutline() {
    const ts = every(74), half = 5.5;
    const pts = [];
    const push = (wx, y) => pts.push([S.W / 2 + rd(wx - S.cam), y]);
    const x0 = S.cam - S.W / 2 - 8, x1 = S.cam + S.W / 2 + 8;
    // walk the span, inserting each tooth's three vertices where it falls
    let tooth = Math.ceil(x0 / ts) * ts;
    for (let wx = x0; wx <= x1; wx += 3) {
      while (tooth < wx && tooth <= x1) {
        const t = caveT(tooth), len = (7 + 9 * Math.abs(Math.sin(wrap(tooth) * 0.021))) * t;
        if (len > 0.6 && roofAt(tooth) > -60) {
          push(tooth - half, roofAt(tooth - half));
          push(tooth, roofAt(tooth) + len);
          push(tooth + half, roofAt(tooth + half));
        }
        tooth += ts;
      }
      push(wx, roofAt(wx));
    }
    return pts;
  }

  /** Clip to everything BELOW the rock, so a tentacle looks like it grows out of
   *  the ceiling instead of hanging in front of it. */
  function clipUnderRoof() {
    const pts = roofOutline();
    g.beginPath();
    g.moveTo(pts[0][0], S.H + 40);
    for (let i = 0; i < pts.length; i++) g.lineTo(pts[i][0], pts[i][1]);
    g.lineTo(pts[pts.length - 1][0], S.H + 40);
    g.closePath();
    g.clip();
  }

  function drawRoof(P) {
    const pts = roofOutline();
    g.beginPath();
    g.moveTo(pts[0][0], -90);
    for (let i = 0; i < pts.length; i++) g.lineTo(pts[i][0], pts[i][1]);
    g.lineTo(pts[pts.length - 1][0], -90);
    g.closePath();
    const rock = g.createLinearGradient(0, -20, 0, ROOF_DARK + 46);
    rock.addColorStop(0, P.rockLo); rock.addColorStop(1, P.rock);
    g.fillStyle = rock; g.fill();
    g.strokeStyle = P.stroke; g.lineWidth = 2; g.lineJoin = "round"; g.lineCap = "round";
    g.beginPath();
    for (let i = 0; i < pts.length; i++) i ? g.lineTo(pts[i][0], pts[i][1]) : g.moveTo(pts[i][0], pts[i][1]);
    g.stroke();
  }


  let darkNow = false;
  function draw() {
    const P = pal();
    if ((P.t > 0.5) !== darkNow) {                            // the title card follows the light
      darkNow = P.t > 0.5;
      document.body.classList.toggle("dark", darkNow);
    }
    const sky = g.createLinearGradient(0, 0, 0, S.H);
    sky.addColorStop(0, P.skyTop); sky.addColorStop(1, P.skyBot);
    g.fillStyle = sky; g.fillRect(0, 0, S.W, S.H);

    ridge(P, 0.18, P.hill, 22, 105);                          // the far skyline
    ridge(P, 0.30, P.hill, 16, 0);
    ridge(P, 0.52, P.hill2, 11, 0);
    drawRoof(P);                                              // the rock overhead
    const vs = every(62);                                     // vines, off the roof
    for (let wx = Math.floor((S.cam - S.W / 2) / vs) * vs; wx < S.cam + S.W / 2 + vs; wx += vs) {
      vine(wx, S.me.t, P, caveT(wx));
    }

    g.beginPath(); g.moveTo(0, S.H);                            // the ground itself
    for (let sx = 0; sx <= S.W; sx += 3) g.lineTo(sx, ground(S.cam + sx - S.W / 2));
    g.lineTo(S.W, S.H); g.closePath();
    const rock = g.createLinearGradient(0, S.base - 40, 0, S.H);
    rock.addColorStop(0, P.rock); rock.addColorStop(1, P.rockLo);
    g.fillStyle = rock; g.fill();
    g.strokeStyle = P.stroke; g.lineWidth = 2; g.lineJoin = "round";
    g.beginPath();
    for (let sx = 0; sx <= S.W; sx += 3) { const y = ground(S.cam + sx - S.W / 2); sx ? g.lineTo(sx, y) : g.moveTo(sx, y); }
    g.stroke();

    for (let i = 0; i < marks.length; i++) {                  // moss banked on the plinths, before the water
      const m = marks[i];                                     // so what dips below the level is seen through it
      if (m.side !== "glossary") continue;
      if (Math.abs(rd(m.x - S.cam)) < S.W / 2 + 60) mossOn(m.x, P, caveT(m.x));
    }
    drawWater(P);                                             // standing water in the dips
    const cs = every(470);                                    // light down the cracks
    for (let wx = Math.floor((S.cam - S.W / 2) / cs) * cs; wx < S.cam + S.W / 2 + cs; wx += cs) {
      crack(wx, S.me.t, P, caveT(wx));
    }
    wayIn(P);                                                 // and the way in from the road

    for (let i = 0; i < marks.length; i++) {                  // the foreground: his own words
      const m = marks[i];
      if (m.side === "penumbra") continue;
      const d = screenX(m);
      if (d > -260 && d < S.W + 260) marker(m, P);
    }

    const gx = active ? clamp(rd(active.x - S.me.x) / 70, -1, 1) : S.me.face * 0.6;
    const gy2 = active && Math.abs(rd(active.x - S.me.x)) < 80 ? -0.85 : -0.1;
    const mx = S.W / 2 + rd(S.me.x - S.cam);                        // the slime, on screen
    gloom(P, mx, ground(S.me.x) - 14);                          // everything unlit goes to black
    g.save();                                                 // the tentacles, masked by the rock
    clipUnderRoof();
    for (let i = 0; i < marks.length; i++) {
      const m = marks[i];
      if (m.side !== "penumbra") continue;
      const d = screenX(m);
      if (d < -220 || d > S.W + 220) continue;
      lines(m);                                               // it needs m.h to know where to grip
      const b = backBand(), gy = b.bottom - m.row * b.gap, top = Math.max(4, gy - m.h);
      // The anchor is the ceiling above the BOARD'S own world position, not above
      // the screen point the board is drawn at. Those differ, because the board is
      // in the far plane: taking the near plane's ceiling made every tentacle slide
      // along the rock's bumps as the camera moved, so they bobbed.
      tentacle(d, roofAt(m.x) - 14, gy - (gy - top) * BACK_SCALE + 2, S.me.t);
    }
    g.restore();
    for (let i = 0; i < marks.length; i++) {                  // the boards are lit, so they survive it
      const m = marks[i];
      if (m.side !== "penumbra") continue;
      const d = screenX(m);
      if (d > -220 && d < S.W + 220) marker(m, P, "board");
    }
    // Only the two mouths are signed, and both are lit, so they are painted
    // after the dark falls rather than under it. The daylight half needs no
    // placard: the page says what it is.
    sign(160, T("glossary.sign.glossary", "Glossary"), P, false,
      T("glossary.sign.glossaryNote",
        "Words I had to coin, because the ones that existed would not do."));
    sign(entryX - 210, T("glossary.sign.antiglossary", "Antiglossary"), P, true,
      T("glossary.sign.antiglossaryNote",
        "Words a machine invented about what my work does not yet say."));
    if (P.t > 0.02) {                                         // motes, only in the dark
      g.fillStyle = P.dust;
      for (let i = 0; i < 26; i++) {
        const seed = i * 97.3;
        const x = wrap((seed * 31) % worldW + (reduce ? 0 : S.me.t * (6 + i % 5)));
        const sx = S.W / 2 + rd(x - S.cam);
        if (sx < -10 || sx > S.W + 10) continue;
        const y = 30 + ((seed * 17) % (S.base - 60)) + Math.sin(S.me.t * 0.7 + i) * 6;
        g.globalAlpha = P.t * 0.7; g.beginPath(); g.arc(sx, y, 1.2, 0, 6.2832); g.fill(); g.globalAlpha = 1;
      }
    }

    if (P.t > 0.05) {
      const lantern = g.createRadialGradient(mx, ground(S.me.x) - 12, 2, mx, ground(S.me.x) - 12, 96);
      lantern.addColorStop(0, "rgba(207,238,224,0.20)"); lantern.addColorStop(1, "rgba(207,238,224,0)");
      g.fillStyle = lantern; g.globalAlpha = P.t; g.fillRect(mx - 90, ground(S.me.x) - 102, 180, 180); g.globalAlpha = 1;
    }
    S.paintBody(S.me.flying ? [gx, 0.2] : [gx, gy2]);        // the slime, where it stands
    vignette(P);                                              // the dark closes in at the edges
    drawSay(mx, (S.me.flying ? S.me.airY : ground(S.me.x)) - 38);   // its words, over the dark
  }

  /* ── the slime says what it can do ──────────────────────────────────────
     Brief tips in the first person, in a bubble over the slime (drawn as the 3D
     village and the iso world draw it), one at a time from a moment after the
     start, each skipped once the reader has done it; a phone gets its own. Once a
     visit. The same words stand in the page (#tips, out of sight) for a screen reader. */
  let saying = null;
  const used = {};
  function sayTip(text, secs) { saying = { text: String(text), t0: performance.now() / 1000, len: secs || 3.4 }; }
  function drawSay(sx, py) {
    if (!saying) return;
    const age = performance.now() / 1000 - saying.t0, left = saying.len - age;
    if (left <= 0) { saying = null; return; }
    const a = Math.max(0, Math.min(1, age * 8, left * 4)), px = 14, hop = (1 - Math.min(1, age * 6)) * px * 0.4;
    g.save(); g.globalAlpha = a;
    g.font = "700 " + px + "px 'Iowan Old Style','Palatino Linotype',Palatino,Georgia,serif";
    const maxW = Math.min(S.W * 0.86, 420), lines = [];
    let line = "";
    for (const word of saying.text.split(" ")) {
      const next = line ? line + " " + word : word;
      if (line && g.measureText(next).width > maxW - px * 1.1) { lines.push(line); line = word; } else line = next;
    }
    if (line) lines.push(line);
    const lh = px * 1.22, w = Math.max(...lines.map((l) => g.measureText(l).width)) + px * 1.1, h = lh * lines.length + px * 0.38;
    const x0 = Math.max(6, Math.min(S.W - w - 6, sx - w / 2)), y0 = py - h - px * 0.6 - hop;
    g.fillStyle = "#ffffff"; g.strokeStyle = "#111111"; g.lineWidth = Math.max(1.2, px * 0.1);
    g.beginPath(); g.roundRect ? g.roundRect(x0, y0, w, h, Math.min(h * 0.45, px * 0.72)) : g.rect(x0, y0, w, h);
    g.moveTo(sx - px * 0.3, y0 + h); g.lineTo(sx - px * 0.05, y0 + h + px * 0.55); g.lineTo(sx + px * 0.25, y0 + h);   // its tail
    g.fill(); g.stroke();
    g.fillStyle = "#ffffff"; g.fillRect(sx - px * 0.25, y0 + h - g.lineWidth, px * 0.46, g.lineWidth * 1.5);
    g.fillStyle = "#111111"; g.textAlign = "center"; g.textBaseline = "middle";
    lines.forEach((l, i) => g.fillText(l, x0 + w / 2, y0 + px * 0.19 + lh * (i + 0.5)));
    g.restore();
  }

  function read() {
    let best = null, bd = 118;
    for (let i = 0; i < marks.length; i++) {
      const d = Math.abs(rd(marks[i].x - S.me.x));
      if (d < bd) { bd = d; best = marks[i]; }
    }
    if (best && best !== active) {
      active = best; best.read = true; show(best);
      if (best === pinned) reached = true;
      else if (reached) { pinned = null; reached = false; }  // walked on from the word it showed
      present();
    }
  }

  function present() { card.hidden = !!(tapOnly && tapOnly.matches) && !(pinned && reached && pinned === active); }
  /** Ask for a word's card (null: none), where cards wait to be asked for. */
  function pin(m) { pinned = m; reached = !!m && m === active; if (m) used.read = true; present(); }
  /** The word whose board, or its post, is under a point on the canvas, in the
   *  view's own units: the same geometry marker() draws. */
  function markAt(px, py) {
    const pad = 8;
    let hit = null;
    for (let i = 0; i < marks.length; i++) {
      const m = marks[i], sx = screenX(m);
      if (sx < -220 || sx > S.W + 220) continue;
      lines(m);
      let on;
      if (m.side === "penumbra") {                           // set back, scaled about where it hangs
        const b = backBand(), gy = b.bottom - m.row * b.gap, top = Math.max(4, gy - m.h), k = BACK_SCALE;
        on = Math.abs(px - sx) <= m.w / 2 * k + pad && py >= gy + (top - gy) * k - pad && py <= gy + (top + m.h - gy) * k + pad;
      } else {
        const gy = ground(m.x), top = gy - 44 - m.row * 24 - m.h;
        on = (Math.abs(px - sx) <= m.w / 2 + pad && py >= top - pad && py <= top + m.h + pad)
          || (Math.abs(px - sx) <= 10 && py > top && py <= gy + pad);
      }
      if (on && (!hit || m.side === "penumbra")) hit = m;    // a board in the dark hangs in front
    }
    return hit;
  }
  if (tapOnly) {
    cv.addEventListener("pointerdown", (ev) => {             // after the engine's own, which aims the walk at the finger
      if (!tapOnly.matches) return;
      const r = cv.getBoundingClientRect();
      const m = markAt((ev.clientX - r.left) * (S.W / r.width), (ev.clientY - r.top) * (S.H / r.height));
      if (m) S.go(m.x);                                      // to the word itself, not the edge of its board
      pin(m);
    });
    if (tapOnly.addEventListener) tapOnly.addEventListener("change", present); else if (tapOnly.addListener) tapOnly.addListener(present);
  }

  /* ── one entry, one address ────────────────────────────────────────────
     Every entry has a slug, and the page keeps it in the query while the slime
     stands there, so any definition can be linked to and cited. A glossary term
     arrives as ?term=, a note from the cave as ?note=. A hash works too, since
     #t-<slug> is that entry's id in the word list and the browser scrolls to it
     without being asked.                                                     */
  const SITE = "https://matthorrigan.com/glossary.html";

  function markFor(slug) {
    if (!slug) return null;
    slug = String(slug).toLowerCase().replace(/^t-/, "");
    for (let i = 0; i < marks.length; i++) if (marks[i].e.slug === slug) return marks[i];
    return null;
  }

  function address(m) {
    let q;
    try { q = new URLSearchParams(location.search); } catch (err) { q = new URLSearchParams(); }
    q.delete("term"); q.delete("note");
    q.set(m.side === "penumbra" ? "note" : "term", m.e.slug);
    return q.toString();
  }

  /** Keep the address in step with where the slime is standing. */
  function stamp(m) {
    try { history.replaceState(null, "", location.pathname + "?" + address(m)); }
    catch (err) { /* some browsers refuse replaceState on file://; no matter */ }
  }

  /** What the cite button copies: a note in Chicago's shape, saying who wrote it. */
  function citation(m) {
    const fr = french(), e = m.e;
    const when = new Date().toLocaleDateString(fr ? "fr-CA" : "en-CA",
      { year: "numeric", month: "long", day: "numeric" });
    const url = SITE + "?" + address(m);
    const title = fr && e.termFr ? e.termFr : e.term;
    if (m.side === "penumbra") {
      return fr
        ? "Claude, \u00ab\u00a0" + title + "\u00a0\u00bb, Antiglossaire, \u00e9crit d\u2019apr\u00e8s les notes de"
          + " M. Reid Horrigan, matthorrigan.com, consult\u00e9 le " + when + ", " + url + "."
        : "Claude, \u201c" + title + ",\u201d Antiglossary, written from the notes of"
          + " M. Reid Horrigan, matthorrigan.com, accessed " + when + ", " + url + ".";
    }
    return fr
      ? "M. Reid Horrigan, \u00ab\u00a0" + title + "\u00a0\u00bb, Glossaire, matthorrigan.com, consult\u00e9 le "
        + when + ", " + url + "."
      : "M. Reid Horrigan, \u201c" + title + ",\u201d Glossary, matthorrigan.com, accessed "
        + when + ", " + url + ".";
  }

  function copy(text, button) {
    const was = button.textContent;
    const done = () => {
      button.textContent = T("glossary.copied", "copied");
      button.classList.add("done");
      setTimeout(() => { button.textContent = was; button.classList.remove("done"); }, 1600);
    };
    const hard = () => {                                     // older Safari, and file://
      const ta = document.createElement("textarea");
      ta.value = text; ta.setAttribute("readonly", "");
      ta.style.cssText = "position:fixed;left:-9999px;top:0";
      document.body.appendChild(ta); ta.select();
      try { document.execCommand("copy"); done(); } catch (err) { /* nothing more to try */ }
      ta.remove();
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(done, hard);
    } else hard();
  }

  /* ── the card under the strip ──────────────────────────────────────── */
  // Said in words. The lexicon's marks (★ coined, ↗ extended, ↺ borrowed) stay in
  // the data as provenance, but a bare arrow on the card explains nothing.
  const KIND = {
    coinage: ["glossary.kind.coinage", "a neologism of mine"],
    "extended-coinage": ["glossary.kind.extendedCoinage", "mine, neologized on somebody else's term"],
    extended: ["glossary.kind.extended", "someone else's term, extended"],
    borrowed: ["glossary.kind.borrowed", "borrowed, and put to work"],
    plain: ["glossary.kind.plain", "in use throughout"],
  };

  function el(tag, cls, text) {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function show(m, quiet) {
    const e = m.e, pen = m.side === "penumbra";
    card.textContent = "";
    card.className = "entry" + (pen ? " pen" : "");
    if (!quiet) stamp(m);                                    // the address follows the slime
    if (pen) {
      card.append(el("h3", null, say(e, "term")));
      card.append(el("p", "gloss", say(e, "gloss")));
      card.append(el("p", "meta", T("glossary.card.note", "Note") + " " + e.id + " · zone:penumbra"));
    } else {
      const k = KIND[e.kind] || KIND.plain;
      card.append(el("p", "kind", T(k[0], k[1])));
      const h = el("h3", null, say(e, "term"));
      if (e.aka && e.aka.length) {
        h.append(" ");
        h.append(el("span", "aka", T("glossary.card.aka", "also") + " " + e.aka.join(", ")));
      }
      if (french() && e.termFr) h.append(" ", el("span", "aka", T("glossary.card.inEnglish", "in English") + " " + e.term));
      card.append(h);
      card.append(el("p", "gloss", say(e, "gloss")));
      const where = [T("glossary.section." + e.section, e.section)];
      if (e.zettel) where.push(e.zettel);
      card.append(el("p", "meta", where.join(" · ")));
    }
    const cite = el("button", "cite", T("glossary.cite", "cite"));
    cite.type = "button";
    cite.title = T("glossary.citeHint", "copy a citation for this entry, with its link");
    cite.addEventListener("click", () => copy(citation(m), cite));
    card.append(cite);
  }

  if (bar) bar.addEventListener("pointerdown", (ev) => {
    const r = bar.getBoundingClientRect();
    S.go(clamp((ev.clientX - r.left) / r.width, 0, 1) * worldW);
    pin(null);
  });

  // The plain-text lists are the same words: clicking one sends the slime to it.
  document.addEventListener("click", (ev) => {
    const b = ev.target && ev.target.closest ? ev.target.closest("dl.words dt button") : null;
    if (!b) return;
    if (b.hasAttribute("data-cite")) {                       // every entry is citeable from the list
      const m = markFor(b.getAttribute("data-cite"));
      if (m) copy(citation(m), b);
      return;
    }
    const side = b.getAttribute("data-side"), i = +b.getAttribute("data-i");
    const m = marks.find((mm) => mm.side === side && mm.i === i);
    if (!m) return;
    S.go(m.x); pin(m);
    cv.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "center" });
    cv.focus({ preventScroll: true });
  });

  document.addEventListener("mh:lang", () => { if (active) show(active); });

  /* The plain-text lists ship their English written out, so they read with no
     script at all. These two rewrite the parts a dictionary cannot reach by
     selector: one section name per term, and the word before an alias. In
     English t() hands back what is already there, so nothing moves. */
  function relabel() {
    Array.prototype.forEach.call(document.querySelectorAll("dl.words .where[data-section]"), (n) => {
      const sec = n.getAttribute("data-section"), z = n.getAttribute("data-zettel");
      n.textContent = [T("glossary.section." + sec, sec), z].filter(Boolean).join(" \u00b7 ");
    });
    Array.prototype.forEach.call(document.querySelectorAll("dl.words dt button[data-fr]"), (n) => {
      if (n.dataset.en == null) n.dataset.en = n.textContent;
      n.textContent = french() ? n.getAttribute("data-fr") : n.dataset.en;
    });
    Array.prototype.forEach.call(document.querySelectorAll("dl.words .g[data-fr]"), (n) => {
      if (n.dataset.en == null) n.dataset.en = n.textContent;   // the English is the page's own
      n.textContent = french() ? n.getAttribute("data-fr") : n.dataset.en;
    });
    Array.prototype.forEach.call(document.querySelectorAll("dl.words dt button[data-cite]"), (n) => {
      n.textContent = T("glossary.cite", "cite");
      n.title = T("glossary.citeHint", "copy a citation for this entry, with its link");
    });
    Array.prototype.forEach.call(document.querySelectorAll("dl.words .aka[data-aka]"), (n) => {
      n.textContent = " " + T("glossary.card.aka", "also") + " " + n.getAttribute("data-aka") + ".";
    });
  }
  relabel();
  document.addEventListener("mh:lang", () => {
    marks.forEach((m) => { m.lines = null; });                // the words themselves changed
    relabel();
  });

  /** Open whatever the address asks for, if it asks for anything. */
  function arrive() {
    let q;
    try { q = new URLSearchParams(location.search); } catch (err) { return false; }
    const want = markFor(q.get("term") || q.get("note"))
      || markFor((location.hash || "").replace(/^#/, ""));
    if (!want) return false;
    S.place(want.x);
    active = want; want.read = true; show(want, true); pin(want);
    return true;
  }

  const counts = { glossary: DATA.glossary.length, penumbra: DATA.antiglossary.length };
  Array.prototype.forEach.call(document.querySelectorAll("[data-count]"), (n) => {
    n.textContent = String(counts[n.getAttribute("data-count")] || "");
  });

  function hello() {
    card.textContent = "";
    card.className = "entry";
    card.append(el("p", "kind", T("glossary.card.start", "the slime is on its way")));
    // (its "Walk to a word" is the slime's to say now, in its bubble)
    card.append(el("p", "gloss", T("glossary.card.startBody",
      "Whatever it reaches is written out here. Past the fissure the light goes"
      + " out and the antiglossary begins, which is not mine.")));
  }
  if (!arrive()) { hello(); present(); }
  {
    const touch = !!(window.matchMedia && window.matchMedia("(pointer: coarse)").matches);
    const tips = touch ? [
      ["walk", "glossary.tip.tap", "I can walk to a word: tap where I should go."],
      ["read", "glossary.tip.read", "I can show you a word's gloss: tap the word."],
    ] : [
      ["walk", "glossary.tip.walk", "I can walk to a word: the arrow keys, or click where I should go."],
      ["hurry", "glossary.tip.hurry", "I can hurry: hold shift."],
    ];
    const tipsEl = document.getElementById("tips");
    const writeTips = () => { if (tipsEl) tipsEl.textContent = tips.map(([, key, en]) => T(key, en)).join(" "); };
    writeTips(); document.addEventListener("mh:lang", writeTips);
    document.addEventListener("keydown", (e) => {
      const k = e.key.toLowerCase();
      if (["arrowleft", "arrowright", "a", "d", "q", "home", "end", "pageup", "pagedown"].includes(k)) used.walk = true;
      if (k === "shift") used.hurry = true;
    });
    cv.addEventListener("pointerdown", () => { used.walk = true; });
    let told = false;
    try { told = !!(window.sessionStorage && sessionStorage.getItem("mh-tips-glossary")); if (!told) sessionStorage.setItem("mh-tips-glossary", "1"); } catch (e) { /* private: tell them anyway */ }
    let i = 0;
    const next = () => {
      while (i < tips.length && used[tips[i][0]]) i++;
      if (i >= tips.length) return;
      const [, key, en] = tips[i++];
      sayTip(T(key, en), 3.6);
      setTimeout(next, 4300);
    };
    if (!told) setTimeout(next, 1400);
  }
  document.addEventListener("mh:lang", () => { if (active) show(active, true); else hello(); });
  window.addEventListener("hashchange", () => {              // a link into the word list
    const m = markFor((location.hash || "").replace(/^#/, ""));
    if (m) { S.go(m.x); pin(m); }
  });

  cv.hidden = false;                                        // it works: show it
  const dock = document.getElementById("dock");
  if (dock) dock.hidden = false;
  document.body.classList.add("live");
  S.size(); draw(); S.observe();
  // Exported so a harness can drive the crawl one frame at a time: headless
  // Chrome does not run requestAnimationFrame in a backgrounded frame, and the
  // walk is worth testing.
  window.MH_GLOSSARY_WORLD = { go: S.go, marks: marks, ground: ground, me: S.me,
    at: () => (active ? label(active) : null), width: () => worldW, dusk: dusk,
    tick: (dt) => S.tick(dt),
    saying: () => (saying && performance.now() / 1000 - saying.t0 < saying.len ? saying.text : ""),   // the slime's words just now
    // what the harness needs to check the layout it cannot see
    layout: () => ({ W: S.W, H: S.H, BASE: S.base, zoom: S.zoom, cam: S.cam, back: BACK,
      scale: BACK_SCALE, band: backBand(), screenX: screenX }),
    cave: () => ({ entryX: entryX, exitX: exitX, mouth: MOUTH, roofLit: ROOF_LIT, roofDark: ROOF_DARK }),
    // a harness taking a picture needs the page to hold still: headless Chrome
    // will not finish a screenshot while a page keeps asking for frames
    pause: S.pause, resume: S.resume,
    caveT: caveT, roofAt: roofAt, rough: rough, entryT: entryT, pools: () => S.pools, side: S,
    cite: (slug) => { const m = markFor(slug); return m ? citation(m) : null; },
    find: markFor };
})();
