// GENERATED by scripts/build-dsp.mjs
/* @ts-self-types="./dsp_core.d.ts" */

class DspEngine {
    __destroy_into_raw() {
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;
        DspEngineFinalization.unregister(this);
        return ptr;
    }
    free() {
        const ptr = this.__destroy_into_raw();
        wasm.__wbg_dspengine_free(ptr, 0);
    }
    /**
     * @returns {number}
     */
    active_voices() {
        const ret = wasm.dspengine_active_voices(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * @returns {number}
     */
    current_frame() {
        const ret = wasm.dspengine_current_frame(this.__wbg_ptr);
        return ret;
    }
    /**
     * @param {number} target_frame
     * @param {number} identity
     * @param {number} action
     * @param {number} value
     * @returns {boolean}
     */
    enqueue_control(target_frame, identity, action, value) {
        const ret = wasm.dspengine_enqueue_control(this.__wbg_ptr, target_frame, identity, action, value);
        return ret !== 0;
    }
    /**
     * @param {number} target_frame
     * @param {number} model
     * @param {number} frequency
     * @param {number} velocity
     * @param {number} duration_seconds
     * @param {number} param_a
     * @param {number} param_b
     * @returns {boolean}
     */
    enqueue_note(target_frame, model, frequency, velocity, duration_seconds, param_a, param_b) {
        const ret = wasm.dspengine_enqueue_note(this.__wbg_ptr, target_frame, model, frequency, velocity, duration_seconds, param_a, param_b);
        return ret !== 0;
    }
    /**
     * @param {number} target_frame
     * @param {number} identity
     * @param {number} model
     * @param {number} frequency
     * @param {number} velocity
     * @param {number} duration_seconds
     * @param {number} param_a
     * @param {number} param_b
     * @param {number} attack_seconds
     * @param {number} release_seconds
     * @param {number} vibrato_depth
     * @param {number} vibrato_rate
     * @returns {boolean}
     */
    enqueue_voice(target_frame, identity, model, frequency, velocity, duration_seconds, param_a, param_b, attack_seconds, release_seconds, vibrato_depth, vibrato_rate) {
        const ret = wasm.dspengine_enqueue_voice(this.__wbg_ptr, target_frame, identity, model, frequency, velocity, duration_seconds, param_a, param_b, attack_seconds, release_seconds, vibrato_depth, vibrato_rate);
        return ret !== 0;
    }
    /**
     * @param {number} sample_rate
     * @param {number} max_voices
     * @param {number} seed
     */
    constructor(sample_rate, max_voices, seed) {
        const ret = wasm.dspengine_new(sample_rate, max_voices, seed);
        this.__wbg_ptr = ret;
        DspEngineFinalization.register(this, this.__wbg_ptr, this);
        return this;
    }
    /**
     * Runs a short deterministic note for browser smoke tests. This is never
     * called from the normal realtime path.
     * @returns {number}
     */
    probe_peak() {
        const ret = wasm.dspengine_probe_peak(this.__wbg_ptr);
        return ret;
    }
    /**
     * @param {number} frames
     * @param {Float32Array} destination
     */
    process(frames, destination) {
        wasm.dspengine_process(this.__wbg_ptr, frames, destination);
    }
    /**
     * @returns {number}
     */
    queued_events() {
        const ret = wasm.dspengine_queued_events(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * @param {number} count
     */
    set_max_voices(count) {
        wasm.dspengine_set_max_voices(this.__wbg_ptr, count);
    }
    /**
     * @param {number} seed
     */
    set_seed(seed) {
        wasm.dspengine_set_seed(this.__wbg_ptr, seed);
    }
    /**
     * @param {number} slot
     * @param {Float32Array} ratios
     * @param {Float32Array} gains
     */
    set_spectrum(slot, ratios, gains) {
        wasm.dspengine_set_spectrum(this.__wbg_ptr, slot, ratios, gains);
    }
    silence() {
        wasm.dspengine_silence(this.__wbg_ptr);
    }
}
if (Symbol.dispose) DspEngine.prototype[Symbol.dispose] = DspEngine.prototype.free;

/**
 * @returns {number}
 */
function abi_version() {
    const ret = wasm.abi_version();
    return ret >>> 0;
}
function __wbg_get_imports() {
    const import0 = {
        __proto__: null,
        __wbg___wbindgen_throw_bb96b2010945f0bc: function(arg0, arg1) {
            throw new Error(getStringFromWasm0(arg0, arg1));
        },
        __wbg_get_index_80f1c5f53c2f2974: function(arg0, arg1) {
            const ret = arg0[arg1 >>> 0];
            return ret;
        },
        __wbg_length_1009454859bb3e03: function(arg0) {
            const ret = arg0.length;
            return ret;
        },
        __wbg_set_577f5f7485b6744e: function(arg0, arg1, arg2) {
            arg0.set(getArrayF32FromWasm0(arg1, arg2));
        },
        __wbg_subarray_095365bb46f94afd: function(arg0, arg1, arg2) {
            const ret = arg0.subarray(arg1 >>> 0, arg2 >>> 0);
            return ret;
        },
        __wbindgen_init_externref_table: function() {
            const table = wasm.__wbindgen_externrefs;
            const offset = table.grow(4);
            table.set(0, undefined);
            table.set(offset + 0, undefined);
            table.set(offset + 1, null);
            table.set(offset + 2, true);
            table.set(offset + 3, false);
        },
    };
    return {
        __proto__: null,
        "./dsp_core_bg.js": import0,
    };
}

const DspEngineFinalization = (typeof FinalizationRegistry === 'undefined')
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry(ptr => wasm.__wbg_dspengine_free(ptr, 1));

function getArrayF32FromWasm0(ptr, len) {
    ptr = ptr >>> 0;
    return getFloat32ArrayMemory0().subarray(ptr / 4, ptr / 4 + len);
}

let cachedFloat32ArrayMemory0 = null;
function getFloat32ArrayMemory0() {
    if (cachedFloat32ArrayMemory0 === null || cachedFloat32ArrayMemory0.byteLength === 0) {
        cachedFloat32ArrayMemory0 = new Float32Array(wasm.memory.buffer);
    }
    return cachedFloat32ArrayMemory0;
}

function getStringFromWasm0(ptr, len) {
    return decodeText(ptr >>> 0, len);
}

let cachedUint8ArrayMemory0 = null;
function getUint8ArrayMemory0() {
    if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
        cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8ArrayMemory0;
}

function decodeText(ptr,len){const bytes=getUint8ArrayMemory0().subarray(ptr,ptr+len);let text='';for(const byte of bytes)text+=String.fromCharCode(byte);return text;}

let wasmModule, wasmInstance, wasm;
function __wbg_finalize_init(instance, module) {
    wasmInstance = instance;
    wasm = instance.exports;
    wasmModule = module;
    cachedFloat32ArrayMemory0 = null;
    cachedUint8ArrayMemory0 = null;
    wasm.__wbindgen_start();
    return wasm;
}

async function __wbg_load(module, imports) {
    if (typeof Response === 'function' && module instanceof Response) {
        if (!module.ok) {
            throw new Error(`failed to fetch Wasm: ${module.status} ${module.statusText} fetching '${module.url}'`);
        }

        if (typeof WebAssembly.instantiateStreaming === 'function') {
            try {
                return await WebAssembly.instantiateStreaming(module, imports);
            } catch (e) {
                const validResponse = expectedResponseType(module.type);

                if (validResponse && module.headers.get('Content-Type') !== 'application/wasm') {
                    console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                } else { throw e; }
            }
        }

        const bytes = await module.arrayBuffer();
        return await WebAssembly.instantiate(bytes, imports);
    } else {
        const instance = await WebAssembly.instantiate(module, imports);

        if (instance instanceof WebAssembly.Instance) {
            return { instance, module };
        } else {
            return instance;
        }
    }

    function expectedResponseType(type) {
        switch (type) {
            case 'basic': case 'cors': case 'default': return true;
        }
        return false;
    }
}

function initSync(module) {
    if (wasm !== undefined) return wasm;


    if (module !== undefined) {
        if (Object.getPrototypeOf(module) === Object.prototype) {
            ({module} = module)
        } else {
            console.warn('using deprecated parameters for `initSync()`; pass a single object instead')
        }
    }

    const imports = __wbg_get_imports();
    if (!(module instanceof WebAssembly.Module)) {
        module = new WebAssembly.Module(module);
    }
    const instance = new WebAssembly.Instance(module, imports);
    return __wbg_finalize_init(instance, module);
}

async function __wbg_init(module_or_path) {
    if (wasm !== undefined) return wasm;


    if (module_or_path !== undefined) {
        if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
            ({module_or_path} = module_or_path)
        } else {
            console.warn('using deprecated parameters for the initialization function; pass a single object instead')
        }
    }

    if (module_or_path === undefined) {
        module_or_path = new URL('dsp_core_bg.wasm', import.meta.url);
    }
    const imports = __wbg_get_imports();

    if (typeof module_or_path === 'string' || (typeof Request === 'function' && module_or_path instanceof Request) || (typeof URL === 'function' && module_or_path instanceof URL)) {
        module_or_path = fetch(module_or_path);
    }

    const { instance, module } = await __wbg_load(await module_or_path, imports);

    return __wbg_finalize_init(instance, module);
}


class MhDspProcessor extends AudioWorkletProcessor {
  constructor(options) {
    super();
    const config = options.processorOptions || {};
    this.renderedEvents=Array(config.busCount||1).fill(0);
    this.generations=Array(config.busCount||1).fill(0);
    this.admittedActions=Array.from({length:config.busCount||1},()=>new Map());
    this.pendingExecution=Array.from({length:config.busCount||1},()=>[]);
    this.executedActions=Array(config.busCount||1).fill(0);
    try {
      initSync({ module: config.module });
      this.engines = Array.from({ length: config.busCount || 1 }, (_, bus) =>
        new DspEngine(sampleRate, config.maxVoices || 16, (config.seed || 1) + bus));
      this.spectrumSlots = this.engines.map(() => new Map());
      this.nextSpectrumSlot = new Uint8Array(this.engines.length);
      this.port.postMessage({ type: "ready", abi: 1 });
    } catch (error) {
      this.engines = [];
      this.port.postMessage({ type: "error", message: String(error && error.stack || error) });
    }
    this.port.onmessage = ({ data }) => {
      const engine = this.engines[data.bus || 0];
      const admission=data.type==='admit'&&engine?this.prepareAdmission(data,engine):null;
      if(admission&&!admission.ok){this.port.postMessage({type:'admission',requestId:data.requestId,bus:data.bus,...admission});return;}
      if ((data.type === "events" || data.type === 'admit') && engine) {
        for (const event of admission?.events || data.events) {
          let paramA = event.paramA || 0;
          if (event.model === 2 && event.ratios?.length && event.gains?.length) {
            const key = `${event.ratios.join(",")}|${event.gains.join(",")}`;
            let slot = this.spectrumSlots[data.bus || 0].get(key);
            if (slot === undefined) {
              slot = this.nextSpectrumSlot[data.bus || 0]++ % 32;
              for(const [oldKey,oldSlot] of this.spectrumSlots[data.bus||0])if(oldSlot===slot)this.spectrumSlots[data.bus||0].delete(oldKey);
              engine.set_spectrum(slot, new Float32Array(event.ratios), new Float32Array(event.gains));
              this.spectrumSlots[data.bus || 0].set(key, slot);
            }
            paramA = slot;
          }
          // The graph may be suspended or disconnected between callbacks.
          // Relate scheduled context time to the engine's current frame now,
          // rather than assuming both clocks have advanced since construction.
          const target=engine.current_frame()+(event.atSeconds===undefined?Math.max(0,Number(event.offsetSeconds)||0):event.atSeconds-currentTime)*sampleRate;
          const p=event.performance||{},identity=event.identity||1;
          if(event.action){
            const ok=engine.enqueue_control(target,identity,event.action,event.value);
            if(!ok)this.port.postMessage({type:'error',bus:data.bus,message:'DSP expression queue is full'});
            if(admission)this.recordAdmission(data,event,target,ok,admission);
            continue;
          }
          const ok=engine.enqueue_voice(target,identity,event.model||0,event.frequency,event.velocity??.7,event.duration??.25,paramA,event.paramB||0,
            p.attackSeconds??.008,p.releaseSeconds??.08,p.vibratoDepth||0,p.vibratoRate||0);
          if(!ok){this.port.postMessage({type:'error',bus:data.bus,message:'DSP note queue is full'});continue}
          if(admission)this.recordAdmission(data,event,target,ok,admission);
          this.renderedEvents[data.bus||0]++;
          for(const control of event.controls||[])if(!engine.enqueue_control(target+control.seconds*sampleRate,identity,control.action,control.value))
            this.port.postMessage({type:'error',bus:data.bus,message:'DSP expression queue is full'});
        }
        if(admission)this.port.postMessage({type:'admission',requestId:data.requestId,bus:data.bus,
          ok:admission.accepted.length===admission.events.length,accepted:admission.accepted,duplicates:admission.duplicates,
          generation:this.generations[data.bus],atContextSeconds:currentTime,executionBoundary:'wasm-queue'});
      } else if(data.type==='configure'&&engine) {
        engine.silence();engine.set_seed(data.seed);
        this.spectrumSlots[data.bus||0].clear();this.nextSpectrumSlot[data.bus||0]=0;
        this.renderedEvents[data.bus||0]=0;
        this.generations[data.bus||0]=data.generation||0;
        this.admittedActions[data.bus||0].clear();this.pendingExecution[data.bus||0]=[];
        this.executedActions[data.bus||0]=0;
      } else if(data.type==='silence'&&engine) {
        engine.silence();
        this.generations[data.bus||0]=data.generation||this.generations[data.bus||0]+1;
        this.pendingExecution[data.bus||0]=[];
      } else if (data.type === "voices" && engine) {
        engine.set_max_voices(data.count);
      } else if (data.type === "diagnostics" && engine) {
        this.port.postMessage({ type: "diagnostics", requestId: data.requestId, bus: data.bus || 0, backend:'wasm-worklet',renderedEvents:this.renderedEvents[data.bus||0],admittedVoices:this.renderedEvents[data.bus||0],executedActions:this.executedActions[data.bus||0],activeVoices: engine.active_voices(), queuedEvents: engine.queued_events(), currentFrame: engine.current_frame() });
      } else if (data.type === "render-probe" && engine) {
        const peak = engine.probe_peak();
        this.port.postMessage({ type: "render-probe", requestId: data.requestId, bus: data.bus || 0, peak, activeVoices: engine.active_voices() });
      }
    };
    this.port.start();
  }

  prepareAdmission(data,engine) {
    const fail=reason=>({ok:false,reason,accepted:[],duplicates:[],executionBoundary:'wasm-queue'});
    if(data.generation!==this.generations[data.bus])return fail('renderer-generation-changed');
    if(!Array.isArray(data.events)||!data.events.length||data.events.length>256)return fail('batch-limit');
    const retained=this.admittedActions[data.bus],seen=new Set(),events=[],duplicates=[];
    for(const [key,value]of retained)if(value.expires<currentTime)retained.delete(key);
    for(const event of data.events) {
      if(typeof event.actionId!=='string'||!event.actionId.length||event.actionId.length>256||seen.has(event.actionId))return fail('invalid-action-identity');
      seen.add(event.actionId);
      const previous=retained.get(event.actionId),fingerprint=JSON.stringify(event);
      if(previous){if(previous.fingerprint!==fingerprint)return fail('conflicting-action');duplicates.push(event.actionId);continue;}
      if(!Number.isFinite(event.atSeconds)||event.atSeconds<currentTime+128/sampleRate||event.atSeconds>currentTime+.25)return fail('outside-audio-window');
      if(!Number.isInteger(event.identity)||event.identity<1||event.identity>0xffffffff||(event.controls?.length||0)>0)return fail('invalid-voice');
      if(event.action) {
        if(![1,2,3,4,5].includes(event.action)||!Number.isFinite(event.value))return fail('invalid-control');
      } else if(!Number.isFinite(event.frequency)||event.frequency<=0||!Number.isFinite(event.duration)||event.duration<0||event.duration>120)return fail('invalid-note');
      events.push(event);
    }
    if(retained.size+events.length>4096||this.pendingExecution[data.bus].length+events.length>1024||engine.queued_events()+events.length>4096)return fail('admission-capacity');
    return {ok:true,events,duplicates,accepted:[]};
  }
  recordAdmission(data,event,target,ok,admission) {
    if(!ok)return;
    admission.accepted.push(event.actionId);
    this.admittedActions[data.bus].set(event.actionId,{fingerprint:JSON.stringify(event),expires:Math.max(currentTime,event.atSeconds+(event.duration||0))+16});
    this.pendingExecution[data.bus].push({actionId:event.actionId,target:Math.floor(target),
      scheduledContextSeconds:event.atSeconds,generation:this.generations[data.bus],kind:event.action?'control':'onset'});
    this.pendingExecution[data.bus].sort((a,b)=>a.target-b.target);
  }

  process(_inputs, outputs) {
    for (let bus = 0; bus < outputs.length; bus++) {
      const output = outputs[bus];
      if (!output || !output.length) continue;
      const mono = output[0];
      const engine = this.engines[bus];
      if (engine) {
        const first=engine.current_frame();engine.process(mono.length, mono);
        const pending=this.pendingExecution[bus];
        while(pending.length&&pending[0].target<engine.current_frame()) {
          const action=pending.shift();this.executedActions[bus]++;
          this.port.postMessage({type:'executed',bus,...action,
            renderedContextSeconds:currentTime+Math.max(0,action.target-first)/sampleRate,
            executionBoundary:'wasm-rendered-frame'});
        }
      } else mono.fill(0);
      for (let channel = 1; channel < output.length; channel++) output[channel].set(mono);
    }
    return true;
  }
}

registerProcessor("musebots-rust-dsp", MhDspProcessor);
